import { Hono } from "hono";
import { and, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/d1";
import type { Env } from "../types/env";
import { invoiceItems, invoices } from "../db/schema";
import { requireAuth, requireAdmin } from "../middleware/auth";
import { createInvoice } from "../services/invoice.service";
import { generateInvoicePdf } from "../services/invoice-pdf.service";

const invoiceRoutes = new Hono<{ Bindings: Env; Variables: { user: { id: number; name: string; email: string; role: number } } }>();
invoiceRoutes.use("*", requireAuth);

invoiceRoutes.get("/", async (c) => {
  const rawPage = Number(c.req.query("page") || 1), rawLimit = Number(c.req.query("limit") || 20); const page = Number.isInteger(rawPage) && rawPage > 0 ? rawPage : 1; const limit = Number.isInteger(rawLimit) && rawLimit > 0 ? Math.min(rawLimit, 100) : 20; const offset = (page - 1) * limit;
  const search = c.req.query("search")?.trim(); const customerId = Number(c.req.query("customerId")); const fromDate = c.req.query("fromDate")?.trim(); const toDate = c.req.query("toDate")?.trim(); const paymentStatus = Number(c.req.query("paymentStatus")); const invoiceStatus = Number(c.req.query("invoiceStatus"));
  const clauses: string[] = ["i.is_deleted = 0"]; const params: unknown[] = [];
  if (search) { clauses.push("(i.invoice_number LIKE ? OR COALESCE(c.name, '') LIKE ? OR COALESCE(i.payment_reference, '') LIKE ?)"); params.push(`%${search}%`, `%${search}%`, `%${search}%`); }
  if (Number.isInteger(customerId) && customerId > 0) { clauses.push("i.customer_id = ?"); params.push(customerId); }
  if (fromDate) { clauses.push("i.invoice_date >= ?"); params.push(`${fromDate}T00:00:00.000Z`); }
  if (toDate) { clauses.push("i.invoice_date < ?"); params.push(`${toDate}T23:59:59.999Z`); }
  if (Number.isInteger(paymentStatus) && paymentStatus >= 0 && paymentStatus <= 4) { clauses.push("i.payment_status = ?"); params.push(paymentStatus); }
  if (Number.isInteger(invoiceStatus) && invoiceStatus >= 0 && invoiceStatus <= 2) { clauses.push("i.invoice_status = ?"); params.push(invoiceStatus); }
  const where = clauses.join(" AND ");
  const result = await c.env.DB.prepare(`SELECT i.*, c.name AS customer_name FROM invoices i LEFT JOIN customers c ON c.id = i.customer_id WHERE ${where} ORDER BY i.id DESC LIMIT ? OFFSET ?`).bind(...params, limit, offset).all();
  const count = await c.env.DB.prepare(`SELECT COUNT(*) AS total FROM invoices i LEFT JOIN customers c ON c.id = i.customer_id WHERE ${where}`).bind(...params).first<{ total: number }>(); const total = count?.total ?? 0;
  return c.json({ invoices: result.results, pagination: { page, limit, total, totalPages: Math.ceil(total / limit) } });
});

invoiceRoutes.get("/:id/pdf", async (c) => { const id = Number(c.req.param("id")); if (!Number.isInteger(id)) return c.json({ error: "Invalid invoice ID" }, 400); const pdf = await generateInvoicePdf(c.env, id); if (!pdf) return c.json({ error: "Invoice not found" }, 404); const invoice = await c.env.DB.prepare("SELECT invoice_number FROM invoices WHERE id = ? AND is_deleted = 0").bind(id).first<{ invoice_number: string }>(); return new Response(pdf, { status: 200, headers: { "Content-Type": "application/pdf", "Content-Disposition": `inline; filename="${invoice?.invoice_number ?? `invoice-${id}`}.pdf"`, "Cache-Control": "private, no-store" } }); });

invoiceRoutes.get("/:id", async (c) => { const id = Number(c.req.param("id")); if (!Number.isInteger(id)) return c.json({ error: "Invalid invoice ID" }, 400); const invoice = await c.env.DB.prepare("SELECT i.*, c.name AS customer_name FROM invoices i LEFT JOIN customers c ON c.id = i.customer_id WHERE i.id = ? AND i.is_deleted = 0").bind(id).first(); if (!invoice) return c.json({ error: "Invoice not found" }, 404); const db = drizzle(c.env.DB); const items = await db.select().from(invoiceItems).where(and(eq(invoiceItems.invoiceId, id), eq(invoiceItems.isDeleted, false))); return c.json({ invoice, items }); });

invoiceRoutes.post("/", async (c) => { try { const body = await c.req.json<{ customerId?: number | null; invoiceDate?: string; dueDate?: string | null; paymentMethod?: number; paymentStatus?: number; paymentReference?: string | null; notes?: string | null; discountAmountPaise?: number; items?: { productId: number; quantity: number }[] }>(); if (!Array.isArray(body.items)) return c.json({ error: "items are required" }, 400); const result = await createInvoice(c.env, c.get("user").id, { ...body, items: body.items }); return c.json({ message: "Invoice created", ...result }, 201); } catch (error) { return c.json({ error: error instanceof Error ? error.message : "Failed to create invoice" }, 400); } });

invoiceRoutes.post("/:id/payment", async (c) => { try { const id = Number(c.req.param("id")); if (!Number.isInteger(id)) return c.json({ error: "Invalid invoice ID" }, 400); const body = await c.req.json<{ paymentStatus?: number; paymentReference?: string | null; paymentMethod?: number }>(); const paymentStatus = body.paymentStatus ?? 1; const paymentMethod = body.paymentMethod; if (![0,1,2,3,4].includes(paymentStatus)) return c.json({ error: "Invalid payment status" }, 400); if (paymentMethod !== undefined && ![0,1,2,3,4].includes(paymentMethod)) return c.json({ error: "Invalid payment method" }, 400); const fields = paymentMethod === undefined ? "payment_status = ?, payment_reference = ?" : "payment_status = ?, payment_method = ?, payment_reference = ?"; const stmt = paymentMethod === undefined ? c.env.DB.prepare(`UPDATE invoices SET ${fields}, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND is_deleted = 0`).bind(paymentStatus, body.paymentReference?.trim() || null, id) : c.env.DB.prepare(`UPDATE invoices SET ${fields}, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND is_deleted = 0`).bind(paymentStatus, paymentMethod, body.paymentReference?.trim() || null, id); const result = await stmt.run(); if ((result.meta.changes ?? 0) !== 1) return c.json({ error: "Invoice not found" }, 404); return c.json({ message: "Payment status updated", invoiceId: id }); } catch (error) { return c.json({ error: error instanceof Error ? error.message : "Failed to update payment" }, 400); } });

invoiceRoutes.post("/:id/cancel", requireAdmin, async (c) => { const id = Number(c.req.param("id")); if (!Number.isInteger(id)) return c.json({ error: "Invalid invoice ID" }, 400); const invoice = await c.env.DB.prepare("SELECT id, invoice_number, invoice_status FROM invoices WHERE id = ? AND is_deleted = 0").bind(id).first<{ id: number; invoice_number: string; invoice_status: number }>(); if (!invoice) return c.json({ error: "Invoice not found" }, 404); if (invoice.invoice_status !== 0) return c.json({ error: "Invoice is already cancelled" }, 409); const items = await c.env.DB.prepare("SELECT product_id, quantity FROM invoice_items WHERE invoice_id = ? AND is_deleted = 0").bind(id).all<{ product_id: number; quantity: number }>(); if (!items.results.length) return c.json({ error: "Invoice has no active items" }, 400); const statements: D1PreparedStatement[] = [c.env.DB.prepare("UPDATE invoices SET invoice_status = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND is_deleted = 0 AND invoice_status = 0").bind(id)]; for (const item of items.results) { statements.push(c.env.DB.prepare("UPDATE products SET stock_quantity = stock_quantity + ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?").bind(item.quantity, item.product_id)); statements.push(c.env.DB.prepare("INSERT INTO inventory_movements (product_id, invoice_id, user_id, movement_type, quantity_change, stock_before, stock_after, reason) SELECT ?, ?, ?, 4, ?, stock_quantity - ?, stock_quantity, ? FROM products WHERE id = ?").bind(item.product_id, id, c.get("user").id, item.quantity, item.quantity, `Invoice cancellation: ${invoice.invoice_number}`, item.product_id)); } const results = await c.env.DB.batch(statements); if (!results[0].success || (results[0].meta.changes ?? 0) !== 1) return c.json({ error: "Invoice was changed by another request; cancellation was not committed" }, 409); for (let i = 1; i < results.length; i += 2) if (!results[i].success || (results[i].meta.changes ?? 0) !== 1) return c.json({ error: "Cancellation failed; transaction was rolled back" }, 400); return c.json({ message: "Invoice cancelled", invoiceId: id, invoiceNumber: invoice.invoice_number }); });

invoiceRoutes.delete("/:id", async (c) => { const id = Number(c.req.param("id")); if (!Number.isInteger(id)) return c.json({ error: "Invalid invoice ID" }, 400); const db = drizzle(c.env.DB); const result = await db.update(invoices).set({ isDeleted: true, updatedAt: new Date().toISOString() }).where(and(eq(invoices.id, id), eq(invoices.isDeleted, false))).returning({ id: invoices.id }); if (!result.length) return c.json({ error: "Invoice not found" }, 404); return c.json({ message: "Invoice deleted" }); });

export default invoiceRoutes;
