import { and, desc, eq, like, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/d1";
import { Hono } from "hono";
import type { Env } from "../types/env";
import { products } from "../db/schema";
import { requireAuth, requireAdmin } from "../middleware/auth";

const productRoutes = new Hono<{ Bindings: Env; Variables: { user: { id: number; name: string; email: string; role: number } } }>();
function getPagination(c: any) { const rawPage=Number(c.req.query("page")||1),rawLimit=Number(c.req.query("limit")||20); const page=Number.isInteger(rawPage)&&rawPage>0?rawPage:1; const limit=Number.isInteger(rawLimit)&&rawLimit>0?Math.min(rawLimit,100):20; return {page,limit,offset:(page-1)*limit}; }
productRoutes.get("/",requireAuth,async c=>{const db=drizzle(c.env.DB);const {page,limit,offset}=getPagination(c);const search=c.req.query("search")?.trim();const where=search?and(eq(products.isDeleted,false),or(like(products.name,`%${search}%`),like(products.sku,`%${search}%`),like(products.barcode,`%${search}%`),like(products.category,`%${search}%`))):eq(products.isDeleted,false);const result=await db.select().from(products).where(where).orderBy(desc(products.id)).limit(limit).offset(offset);const count=await c.env.DB.prepare(search?"SELECT COUNT(*) AS total FROM products WHERE is_deleted = 0 AND (name LIKE ? OR sku LIKE ? OR barcode LIKE ? OR category LIKE ?)":"SELECT COUNT(*) AS total FROM products WHERE is_deleted = 0").bind(...(search?[`%${search}%`,`%${search}%`,`%${search}%`,`%${search}%`]:[])).first<{total:number}>();const total=count?.total??0;return c.json({products:result,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}})});
productRoutes.get("/:id",requireAuth,async c=>{const id=Number(c.req.param("id"));if(!Number.isInteger(id))return c.json({error:"Invalid product ID"},400);const db=drizzle(c.env.DB);const result=await db.select().from(products).where(and(eq(products.id,id),eq(products.isDeleted,false))).limit(1);if(!result.length)return c.json({error:"Product not found"},404);return c.json({product:result[0]})});
productRoutes.post("/",requireAuth,requireAdmin,async c=>{const body=await c.req.json<{name?:string;sku?:string;hsnCode?:string;unit?:string;sellingPricePaise?:number;gstRate?:number;stockQuantity?:number;reorderLevel?:number;purchasePricePaise?:number;category?:string;barcode?:string}>();if(!body.name?.trim()||!body.sku?.trim())return c.json({error:"Name and SKU are required"},400);const numeric=[['sellingPricePaise',body.sellingPricePaise],['stockQuantity',body.stockQuantity??0],['gstRate',body.gstRate??0],['reorderLevel',body.reorderLevel??0],['purchasePricePaise',body.purchasePricePaise??0]];for(const [name,value]of numeric){if(!Number.isInteger(value as number)||(value as number)<0||name==='gstRate'&&(value as number)>100)return c.json({error:`${name} is invalid`},400)}const db=drizzle(c.env.DB);try{const result=await db.insert(products).values({name:body.name.trim(),sku:body.sku.trim(),hsnCode:body.hsnCode?.trim()||null,unit:body.unit?.trim()||"PCS",sellingPricePaise:body.sellingPricePaise as number,gstRate:body.gstRate??0,stockQuantity:body.stockQuantity??0,reorderLevel:body.reorderLevel??0,purchasePricePaise:body.purchasePricePaise??0,category:body.category?.trim()||null,barcode:body.barcode?.trim()||null,isDeleted:false}).returning();return c.json({message:"Product created",product:result[0]},201)}catch{return c.json({error:"SKU already exists"},409)}});
productRoutes.put("/:id",requireAuth,requireAdmin,async c=>{const id=Number(c.req.param("id"));if(!Number.isInteger(id))return c.json({error:"Invalid product ID"},400);const body=await c.req.json<any>();const updateData:any={updatedAt:new Date().toISOString()};for(const [key,column]of [['name','name'],['sku','sku'],['hsnCode','hsnCode'],['unit','unit'],['sellingPricePaise','sellingPricePaise'],['gstRate','gstRate'],['stockQuantity','stockQuantity'],['reorderLevel','reorderLevel'],['purchasePricePaise','purchasePricePaise'],['category','category'],['barcode','barcode']])if(body[key]!==undefined){if(['sellingPricePaise','gstRate','stockQuantity','reorderLevel','purchasePricePaise'].includes(key)&&(!Number.isInteger(body[key])||body[key]<0||(key==='gstRate'&&body[key]>100)))return c.json({error:`${key} is invalid`},400);updateData[column]=typeof body[key]==='string'?(body[key].trim()||null):body[key]}const db=drizzle(c.env.DB);try{const result=await db.update(products).set(updateData).where(and(eq(products.id,id),eq(products.isDeleted,false))).returning();if(!result.length)return c.json({error:"Product not found"},404);return c.json({message:"Product updated",product:result[0]})}catch{return c.json({error:"SKU already exists"},409)}});
productRoutes.delete("/:id",requireAuth,requireAdmin,async c=>{const id=Number(c.req.param("id"));if(!Number.isInteger(id))return c.json({error:"Invalid product ID"},400);const db=drizzle(c.env.DB);const result=await db.update(products).set({isDeleted:true,updatedAt:new Date().toISOString()}).where(and(eq(products.id,id),eq(products.isDeleted,false))).returning({id:products.id,name:products.name,isDeleted:products.isDeleted});if(!result.length)return c.json({error:"Product not found"},404);return c.json({message:"Product deleted",product:result[0]})});
export default productRoutes;
